version: "3.9"

services:
  app-dev:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: Dockerfile
      target: development-dependencies-env
    working_dir: /app
    command: npm run dev
    environment:
      NODE_ENV: development
      # Helpful for file-watching on Windows/WSL/Docker Desktop
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5176:5173"
    

  app-prod:
    profiles: ["prod"]
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"

networks:
  shared:
    external: true